@HostAddress = https://sms.ir-trades.com
@LocalAddress = https://localhost:7100

GET {{HostAddress}}/Messenjoor
Accept: application/json

###

GET {{HostAddress}}/Messenjoor/TestDb
Accept: application/json

###

POST {{HostAddress}}/account/login
Content-Type: application/json
#Accept-Language: en-US,en;q=0.5

{
    "Username": "user3",
    "Password": "123"
}

###

POST {{HostAddress}}/account/register
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1MzBhMWY4Yi1kMTdjLTRmZDAtYjM0MC1mNDFkNzBkMDZlNWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoi2KfZgdiz2KfZhtmHIiwiZXhwIjoxNzEyNDM5MzE3LCJpc3MiOiJodHRwczovL21lc3Nlbmpvb3IuaXIiLCJhdWQiOiIqIn0.mFHomDhmgqxqgeH9ZAqpEA3jd0-6ICSsrCIdT5LKLyM
#Accept-Language: en-US,en;q=0.5

{
    "Name":"کاترین",
    "Username": "user5",
    "Password": "123"
}

###

POST {{HostAddress}}/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1MzBhMWY4Yi1kMTdjLTRmZDAtYjM0MC1mNDFkNzBkMDZlNWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoi2KfZgdiz2KfZhtmHIiwiZXhwIjoxNzEyNDM5MzE3LCJpc3MiOiJodHRwczovL21lc3Nlbmpvb3IuaXIiLCJhdWQiOiIqIn0.mFHomDhmgqxqgeH9ZAqpEA3jd0-6ICSsrCIdT5LKLyM
#Accept-Language: en-US,en;q=0.5

{
  "toUserId": 1,
  "message": "سلام"
}

###

POST https://f2c3249c-86c4-41e9-9fdb-d3a644514b27.pushnotifications.pusher.com/publish_api/v1/instances/f2c3249c-86c4-41e9-9fdb-d3a644514b27/publishes
Content-Type: application/json
Authorization: Bearer 0F28E168CC3CDCB9E0018E0C7AF7B17307733A499B96029A8DAF7BFF863A3AF9
#Accept-Language: en-US,en;q=0.5

{"interests":["1"],"web":{"notification":{"title":"Hello","body":"Hello, world!"}}}


###

                                                                            
                                                                            
POST https://f2c3249c-86c4-41e9-9fdb-d3a644514b27.pushnotifications.pusher.com/device_api/v1/instances/f2c3249c-86c4-41e9-9fdb-d3a644514b27/devices/web
Content-Type: application/json
Authorization: Bearer 0F28E168CC3CDCB9E0018E0C7AF7B17307733A499B96029A8DAF7BFF863A3AF9


{"token":""}